export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN_SUCCESS = 'LOGGED_IN_SUCCESS';
export const LOGGED_IN_FAILED = 'LOGGED_IN_FAILED';
export const LOG_OUT = 'LOG_OUT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_ALL_STANDARDS = 'GET_ALL_STANDARDS';
export const GET_ALL_STANDARDS_SUCCESS = 'GET_ALL_STANDARDS_SUCCESS';
export const GET_ALL_STANDARDS_FAILED = 'GET_ALL_STANDARDS_FAILED';

export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAILED = 'GET_ALL_COURSES_FAILED';

export const GET_ALL_CURRICULA = 'GET_ALL_CURRICULA';
export const GET_ALL_CURRICULA_SUCCESS = 'GET_ALL_CURRICULA_SUCCESS';
export const GET_ALL_CURRICULA_FAILED = 'GET_ALL_CURRICULA_FAILED';

export const GET_STANDARD = 'GET_STANDARD';
export const GET_STANDARD_SUCCESS = 'GET_STANDARD_SUCCESS';
export const GET_STANDARD_FAILED = 'GET_STANDARD_FAILED';

export const GET_COURSE = 'GET_COURSE';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_FAILED = 'GET_COURSE_FAILED';

export const GET_CURRICULUM = 'GET_CURRICULUM';
export const GET_CURRICULUM_SUCCESS = 'GET_CURRICULUM_SUCCESS';
export const GET_CURRICULUM_FAILED = 'GET_CURRICULUM_FAILED';

export const GET_CURRICULUM_COMPETENCIES = 'GET_CURRICULUM_COMPETENCIES';
export const GET_CURRICULUM_COMPETENCIES_SUCCESS = 'GET_CURRICULUM_COMPETENCIES_SUCCESS';
export const GET_CURRICULUM_COMPETENCIES_FAILED = 'GET_CURRICULUM_COMPETENCIES_FAILED';

export const GET_CURRICULUM_MODULES = 'GET_CURRICULUM_MODULES';
export const GET_CURRICULUM_MODULES_SUCCESS = 'GET_CURRICULUM_MODULES_SUCCESS';
export const GET_CURRICULUM_MODULES_FAILED = 'GET_CURRICULUM_MODULES_FAILED';

export const GET_CURRICULUM_COURSES = 'GET_CURRICULUM_COURSES';
export const GET_CURRICULUM_COURSES_SUCCESS = 'GET_CURRICULUM_COURSES_SUCCESS';
export const GET_CURRICULUM_COURSES_FAILED = 'GET_CURRICULUM_COURSES_FAILED';

export const GET_CURRICULUM_COMPLIANCE = 'GET_CURRICULUM_COMPLIANCE';
export const GET_CURRICULUM_COMPLIANCE_SUCCESS = 'GET_CURRICULUM_COMPLIANCE_SUCCESS';
export const GET_CURRICULUM_COMPLIANCE_FAILED = 'GET_CURRICULUM_COMPLIANCE_FAILED';

export const GET_FREEFORM_COMPETENCIES = 'GET_FREEFORM_COMPETENCIES';
export const GET_FREEFORM_COMPETENCIES_SUCCESS = 'GET_FREEFORM_COMPETENCIES_SUCCESS';
export const GET_FREEFORM_COMPETENCIES_FAILED = 'GET_FREEFORM_COMPETENCIES_FAILED';

export const SAVE_STANDARD = 'SAVE_STANDARD';
export const SAVE_STANDARD_SUCCESS = 'SAVE_STANDARD_SUCCESS';
export const SAVE_STANDARD_FAILED = 'SAVE_STANDARD_FAILED';

export const SAVE_COURSE = 'SAVE_COURSE';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const SAVE_COURSE_FAILED = 'SAVE_COURSE_FAILED';

export const SAVE_CURRICULUM = 'SAVE_CURRICULUM';
export const SAVE_CURRICULUM_SUCCESS = 'SAVE_CURRICULUM_SUCCESS';
export const SAVE_CURRICULUM_FAILED = 'SAVE_CURRICULUM_FAILED';

export const SET_FREEFORM_COMPETENCIES = 'SET_FREEFORM_COMPETENCIES';

export const SAVE_FREEFORM_COMPETENCY = 'SAVE_FREEFORM_COMPETENCY';
export const SAVE_FREEFORM_COMPETENCY_SUCCESS = 'SAVE_FREEFORM_COMPETENCY_SUCCESS';
export const SAVE_FREEFORM_COMPETENCY_FAILED = 'SAVE_FREEFORM_COMPETENCY_FAILED';

export const ADD_COMPETENCY = 'ADD_COMPETENCY';
export const ADD_SKILL = 'ADD_SKILl';
export const ADD_KNOWLEDGE = 'ADD_KNOWLEDGE';

export const REMOVE_COMPETENCY = 'REMOVE_COMPETENCY';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const REMOVE_KNOWLEDGE = 'REMOVE_KNOWLEDGE';

export const SET_SKILL = 'SET_SKILL';
export const SET_KNOWLEDGE = 'SET_KNOWLEDGE';

export const CHANGE_STANDARD_FIELD = 'CHANGE_STANDARD_FIELD';
export const CHANGE_COURSE_FIELD = 'CHANGE_COURSE_FIELD';
export const CHANGE_CURRICULUM_FIELD = 'CHANGE_CURRICULUM_FIELD';
export const CHANGE_PROFILE_FIELD = 'CHANGE_PROFILE_FIELD';

export const CHANGE_COMPETENCY_NAME = 'CHANGE_COMPETENCY_NAME';

export const ADD_COURSE_COMPETENCY = 'ADD_COURSE_COMPETENCY';
export const REMOVE_COURSE_COMPETENCY = 'REMOVE_COURSE_COMPETENCY';

export const SET_MODULE_COURSES = 'SET_MODULE_COURSES';

export const ADD_MODULE = 'ADD_MODULE';
export const CHANGE_MODULE_FIELD = 'CHANGE_MODULE_FIELD';
export const REMOVE_MODULE = 'REMOVE_MODULE';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED= 'GET_PROFILE_FAILED';

export const SAVE_PROFILE = 'SAVE_PROFILE';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILED = 'SAVE_PROFILE_FAILED';
